<a href="https://colab.research.google.com/github/Kanackle/ATPWinnersAnalysis/blob/main/Tennis_Matches.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import io
import glob
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#Put the files in google drive so it is easier to open
files = glob.glob('/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/*.csv')
print(files)  # Verify it finds your files

['/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2016.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2006.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2014.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2005.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2003.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2018.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2019.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2004.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2010.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2008.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2011.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2012.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2017.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2013.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2020.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2007.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2015.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2009.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2001.csv', '/content/drive/MyDrive/Colab Notebooks/Tennis Matches Data/archive (5)/atp_matches_2002.csv']

In [ ]:
#checking size of df
df = pd.concat([pd.read_csv(f) for f in files])
print(df.shape)

(59789, 49)

In [ ]:
#making a separate year column
dfs = []
for f in files:
    temp = pd.read_csv(f)
    temp["year"] = f.split("_")[2].replace(".csv", "")  # adjust based on your filename pattern
    dfs.append(temp)

df = pd.concat(dfs, ignore_index=True)

In [ ]:
df['year'] = df['year'].astype(int)

In [ ]:
#make sure all data types are valid
df.dtypes

tourney_id             object
tourney_name           object
surface                object
draw_size               int64
tourney_level          object
tourney_date            int64
match_num               int64
winner_id               int64
winner_seed           float64
winner_entry           object
winner_name            object
winner_hand            object
winner_ht             float64
winner_ioc             object
winner_age            float64
loser_id                int64
loser_seed            float64
loser_entry            object
loser_name             object
loser_hand             object
loser_ht              float64
loser_ioc              object
loser_age             float64
score                  object
best_of                 int64
round                  object
minutes               float64
w_ace                 float64
w_df                  float64
w_svpt                float64
w_1stIn               float64
w_1stWon              float64
w_2ndWon              float64
w_SvGms               float64
w_bpSaved             float64
w_bpFaced             float64
l_ace                 float64
l_df                  float64
l_svpt                float64
l_1stIn               float64
l_1stWon              float64
l_2ndWon              float64
l_SvGms               float64
l_bpSaved             float64
l_bpFaced             float64
winner_rank           float64
winner_rank_points    float64
loser_rank            float64
loser_rank_points     float64
year                    int64
dtype: object

In [ ]:
df["w_ace"].apply(type).value_counts()

w_ace
<class 'float'>    59789
Name: count, dtype: int64

In [ ]:
#Filter out for only masters and grand slam level tournaments
mastersPlus = df[
    (df['tourney_level'] == 'M') |
    (df['tourney_level'] == 'G')
    ].sort_values(['tourney_date', 'match_num']).reset_index(drop=True)

mastersPlus

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
0,2001-580,Australian Open,Hard,128,G,20010115,1,102856,1.0,NaN,...,61.0,29.0,22.0,10.0,16.0,1.0,4195.0,38.0,945.0,2001
1,2001-580,Australian Open,Hard,128,G,20010115,2,102257,NaN,NaN,...,46.0,27.0,19.0,3.0,8.0,65.0,625.0,202.0,188.0,2001
2,2001-580,Australian Open,Hard,128,G,20010115,3,102905,NaN,NaN,...,41.0,23.0,18.0,5.0,11.0,48.0,780.0,112.0,364.0,2001
3,2001-580,Australian Open,Hard,128,G,20010115,4,102694,NaN,Q,...,74.0,34.0,27.0,11.0,18.0,185.0,208.0,99.0,412.0,2001
4,2001-580,Australian Open,Hard,128,G,20010115,5,102765,NaN,NaN,...,77.0,30.0,26.0,12.0,18.0,46.0,840.0,74.0,552.0,2001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21037,2020-0352,Paris Masters,Hard,64,M,20201102,296,100644,4.0,NaN,...,23.0,14.0,11.0,0.0,4.0,7.0,5015.0,20.0,2230.0,2020
21038,2020-0352,Paris Masters,Hard,64,M,20201102,297,104745,1.0,NaN,...,46.0,11.0,14.0,4.0,7.0,2.0,9850.0,15.0,2400.0,2020
21039,2020-0352,Paris Masters,Hard,64,M,20201102,298,106421,3.0,NaN,...,38.0,6.0,11.0,1.0,3.0,5.0,5980.0,17.0,2265.0,2020
21040,2020-0352,Paris Masters,Hard,64,M,20201102,299,100644,4.0,NaN,...,29.0,12.0,11.0,5.0,8.0,7.0,5015.0,2.0,9850.0,2020
21041,2020-0352,Paris Masters,Hard,64,M,20201102,300,106421,3.0,NaN,...,51.0,9.0,15.0,6.0,10.0,5.0,5980.0,7.0,5015.0,2020

In [ ]:
#Drop all unnecessary columns
mastersPlus = mastersPlus.drop(columns = ['tourney_id', 'draw_size', 'tourney_level', 'tourney_date', 'winner_id', 'winner_entry', 'winner_hand', 'loser_id', 'loser_entry', 'loser_hand', 'winner_rank', 'winner_rank_points', 'loser_rank', 'loser_rank_points'])

mastersPlus

,tourney_name,surface,match_num,winner_seed,winner_name,winner_ht,winner_ioc,winner_age,loser_seed,loser_name,...,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,year
0,Australian Open,Hard,1,1.0,Gustavo Kuerten,190.0,BRA,24.347707,NaN,Gaston Gaudio,...,8.0,6.0,153.0,85.0,61.0,29.0,22.0,10.0,16.0,2001
1,Australian Open,Hard,2,NaN,Greg Rusedski,193.0,GBR,27.359343,NaN,Marcos Ondruska,...,1.0,6.0,124.0,70.0,46.0,27.0,19.0,3.0,8.0,2001
2,Australian Open,Hard,3,NaN,Stefan Koubek,175.0,AUT,24.035592,NaN,Jeff Tarango,...,10.0,3.0,106.0,61.0,41.0,23.0,18.0,5.0,11.0,2001
3,Australian Open,Hard,4,NaN,Lars Burgsmuller,183.0,GER,25.111567,NaN,Daniel Elsner,...,7.0,11.0,182.0,98.0,74.0,34.0,27.0,11.0,18.0,2001
4,Australian Open,Hard,5,NaN,Nicolas Escude,185.0,FRA,24.785763,NaN,Juan Balcells,...,8.0,1.0,169.0,113.0,77.0,30.0,26.0,12.0,18.0,2001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21037,Paris Masters,Hard,296,4.0,Alexander Zverev,198.0,GER,23.537303,12.0,Stan Wawrinka,...,2.0,1.0,65.0,36.0,23.0,14.0,11.0,0.0,4.0,2020
21038,Paris Masters,Hard,297,1.0,Rafael Nadal,185.0,ESP,34.417522,9.0,Pablo Carreno Busta,...,4.0,0.0,92.0,68.0,46.0,11.0,14.0,4.0,7.0,2020
21039,Paris Masters,Hard,298,3.0,Daniil Medvedev,198.0,RUS,24.725530,10.0,Milos Raonic,...,12.0,1.0,68.0,47.0,38.0,6.0,11.0,1.0,3.0,2020
21040,Paris Masters,Hard,299,4.0,Alexander Zverev,198.0,GER,23.537303,1.0,Rafael Nadal,...,5.0,0.0,68.0,46.0,29.0,12.0,11.0,5.0,8.0,2020
21041,Paris Masters,Hard,300,3.0,Daniil Medvedev,198.0,RUS,24.725530,4.0,Alexander Zverev,...,11.0,3.0,102.0,76.0,51.0,9.0,15.0,6.0,10.0,2020

In [ ]:
from google.colab import files
#Export df into csv file
pd.DataFrame(mastersPlus).to_csv('mastersPlus.csv', index=False)

#Download file to computer rather than colab storage
files.download('mastersPlus.csv')

In [ ]:
#Filter out only for Round of 16(end goal is to get only the top 8 players -> winners of R16)
R16Winners = mastersPlus[
    (mastersPlus['round'] == 'R16')
]

R16Winners

,tourney_name,surface,match_num,winner_seed,winner_name,winner_ht,winner_ioc,winner_age,loser_seed,loser_name,...,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,year
112,Australian Open,Hard,113,15.0,Arnaud Clement,173.0,FRA,23.080082,NaN,Greg Rusedski,...,19.0,5.0,109.0,59.0,44.0,17.0,15.0,10.0,15.0,2001
113,Australian Open,Hard,114,4.0,Yevgeny Kafelnikov,190.0,RUS,26.907598,NaN,Andreas Vinciguerra,...,4.0,6.0,108.0,51.0,34.0,23.0,16.0,10.0,17.0,2001
114,Australian Open,Hard,115,16.0,Sebastien Grosjean,175.0,FRA,22.633812,5.0,Magnus Norman,...,8.0,0.0,112.0,63.0,45.0,27.0,19.0,4.0,8.0,2001
115,Australian Open,Hard,116,NaN,Carlos Moya,190.0,ESP,24.386037,NaN,Rainer Schuettler,...,6.0,4.0,86.0,54.0,42.0,14.0,16.0,2.0,5.0,2001
116,Australian Open,Hard,117,6.0,Andre Agassi,180.0,USA,30.715948,NaN,Andrew Ilie,...,6.0,6.0,141.0,88.0,55.0,21.0,18.0,18.0,26.0,2001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21030,Paris Masters,Hard,289,6.0,Diego Schwartzman,170.0,ARG,28.213552,NaN,Alejandro Davidovich Fokina,...,0.0,2.0,34.0,20.0,9.0,3.0,7.0,1.0,6.0,2020
21031,Paris Masters,Hard,290,12.0,Stan Wawrinka,183.0,SUI,35.600274,5.0,Andrey Rublev,...,10.0,4.0,77.0,49.0,35.0,15.0,13.0,2.0,5.0,2020
21032,Paris Masters,Hard,291,4.0,Alexander Zverev,198.0,GER,23.537303,NaN,Adrian Mannarino,...,9.0,7.0,137.0,77.0,60.0,25.0,17.0,7.0,11.0,2020
21033,Paris Masters,Hard,292,9.0,Pablo Carreno Busta,188.0,ESP,29.311431,NaN,Norbert Gombos,...,2.0,2.0,54.0,30.0,17.0,7.0,10.0,4.0,10.0,2020
21034,Paris Masters,Hard,293,1.0,Rafael Nadal,185.0,ESP,34.417522,NaN,Jordan Thompson,...,7.0,0.0,56.0,39.0,29.0,6.0,9.0,2.0,4.0,2020

In [ ]:
print(R16Winners[['tourney_name','year','winner_name']])

          tourney_name  year          winner_name
112    Australian Open  2001       Arnaud Clement
113    Australian Open  2001   Yevgeny Kafelnikov
114    Australian Open  2001   Sebastien Grosjean
115    Australian Open  2001          Carlos Moya
116    Australian Open  2001         Andre Agassi
...                ...   ...                  ...
21030    Paris Masters  2020    Diego Schwartzman
21031    Paris Masters  2020        Stan Wawrinka
21032    Paris Masters  2020     Alexander Zverev
21033    Paris Masters  2020  Pablo Carreno Busta
21034    Paris Masters  2020         Rafael Nadal

[2024 rows x 3 columns]

In [ ]:
#Get all winners of R16 into a set per tournament
Top8Winners = R16Winners.groupby(['tourney_name', 'year'])['winner_name'].apply(set).reset_index()

Top8Winners.head(50)

,tourney_name,year,winner_name
0,Australian Open,2001,"{Yevgeny Kafelnikov, Sebastien Grosjean, Arnau..."
1,Australian Open,2002,"{Jiri Novak, Wayne Ferreira, Marat Safin, Stef..."
2,Australian Open,2003,"{Sebastien Grosjean, David Nalbandian, Wayne F..."
3,Australian Open,2004,"{Sebastien Grosjean, David Nalbandian, Roger F..."
4,Australian Open,2005,"{Roger Federer, David Nalbandian, Andy Roddick..."
5,Australian Open,2006,"{Sebastien Grosjean, Marcos Baghdatis, Roger F..."
6,Australian Open,2007,"{Roger Federer, Andy Roddick, Tommy Haas, Tomm..."
7,Australian Open,2008,"{James Blake, Roger Federer, David Ferrer, Mik..."
8,Australian Open,2009,"{Roger Federer, Andy Roddick, Gilles Simon, Jo..."
9,Australian Open,2010,"{Roger Federer, Andy Roddick, Marin Cilic, Jo-..."
10,Australian Open,2011,"{Roger Federer, Stan Wawrinka, David Ferrer, T..."
11,Australian Open,2012,"{Roger Federer, Kei Nishikori, David Ferrer, T..."
12,Australian Open,2013,"{Jeremy Chardy, Roger Federer, Nicolas Almagro..."
13,Australian Open,2014,"{Roger Federer, Stan Wawrinka, David Ferrer, G..."
14,Australian Open,2015,"{Stan Wawrinka, Kei Nishikori, Milos Raonic, T..."
15,Australian Open,2016,"{Roger Federer, Kei Nishikori, David Ferrer, M..."
16,Australian Open,2017,"{Roger Federer, Stan Wawrinka, Milos Raonic, D..."
17,Australian Open,2018,"{Roger Federer, Tennys Sandgren, Grigor Dimitr..."
18,Australian Open,2019,"{Kei Nishikori, Milos Raonic, Rafael Nadal, Ro..."
19,Australian Open,2020,"{Roger Federer, Stan Wawrinka, Tennys Sandgren..."
20,Canada Masters,2001,"{Arnaud Clement, Andy Roddick, Bohdan Ulihrach..."
21,Canada Masters,2002,"{Sebastien Grosjean, David Nalbandian, Andy Ro..."
22,Canada Masters,2003,"{Feliciano Lopez, David Nalbandian, Roger Fede..."
23,Canada Masters,2004,"{Roger Federer, Jan Hernych, Andy Roddick, Joa..."
24,Canada Masters,2005,"{Karol Beck, Mariano Puerta, Rafael Nadal, And..."
25,Canada Masters,2006,"{Roger Federer, Jose Acasuso, Tomas Berdych, X..."
26,Canada Masters,2007,"{Radek Stepanek, Roger Federer, Andy Roddick, ..."
27,Canada Masters,2008,"{James Blake, Gilles Simon, Marin Cilic, Richa..."
28,Canada Masters,2009,"{Roger Federer, Andy Roddick, Jo-Wilfried Tson..."
29,Canada Masters,2010,"{David Nalbandian, Roger Federer, Jeremy Chard..."
30,Canada Masters,2011,"{Stan Wawrinka, Nicolas Almagro, Janko Tipsare..."
31,Canada Masters,2012,"{Milos Raonic, Janko Tipsarevic, John Isner, T..."
32,Canada Masters,2013,"{Marinko Matosevic, Vasek Pospisil, Ernests Gu..."
33,Canada Masters,2014,"{Feliciano Lopez, Roger Federer, David Ferrer,..."
34,Canada Masters,2015,"{Jeremy Chardy, Kei Nishikori, Ernests Gulbis,..."
35,Canada Masters,2016,"{Stan Wawrinka, Kei Nishikori, Milos Raonic, G..."
36,Canada Masters,2017,"{Roger Federer, Robin Haase, Diego Schwartzman..."
37,Canada Masters,2018,"{Robin Haase, Alexander Zverev, Karen Khachano..."
38,Canada Masters,2019,"{Fabio Fognini, Alexander Zverev, Dominic Thie..."
39,Cincinnati Masters,2001,"{Yevgeny Kafelnikov, Tim Henman, Patrick Rafte..."
40,Cincinnati Masters,2002,"{Andy Roddick, Carlos Moya, Juan Carlos Ferrer..."
41,Cincinnati Masters,2003,"{David Nalbandian, Andy Roddick, Mariano Zabal..."
42,Cincinnati Masters,2004,"{Andy Roddick, Carlos Moya, Marat Safin, Fabri..."
43,Cincinnati Masters,2005,"{Roger Federer, Andy Roddick, Mikhail Youzhny,..."
44,Cincinnati Masters,2006,"{Andy Roddick, David Ferrer, Juan Carlos Ferre..."
45,Cincinnati Masters,2007,"{James Blake, Roger Federer, Carlos Moya, Nico..."
46,Cincinnati Masters,2008,"{Carlos Moya, Ernests Gulbis, Philipp Kohlschr..."
47,Cincinnati Masters,2009,"{Roger Federer, Gilles Simon, Tomas Berdych, J..."
48,Cincinnati Masters,2010,"{Marcos Baghdatis, Roger Federer, Andy Roddick..."
49,Cincinnati Masters,2011,"{Roger Federer, Gilles Simon, Tomas Berdych, R..."

In [ ]:
Top8Winners.columns = ['tourney_name', 'year', 'top8_players']

Top8Winners

        tourney_name  year                                       top8_players
0    Australian Open  2001  {Yevgeny Kafelnikov, Sebastien Grosjean, Arnau...
1    Australian Open  2002  {Jiri Novak, Wayne Ferreira, Marat Safin, Stef...
2    Australian Open  2003  {Sebastien Grosjean, David Nalbandian, Wayne F...
3    Australian Open  2004  {Sebastien Grosjean, David Nalbandian, Roger F...
4    Australian Open  2005  {Roger Federer, David Nalbandian, Andy Roddick...
..               ...   ...                                                ...
248        Wimbledon  2015  {Roger Federer, Stan Wawrinka, Gilles Simon, V...
249        Wimbledon  2016  {Roger Federer, Sam Querrey, Milos Raonic, Tom...
250        Wimbledon  2017  {Roger Federer, Sam Querrey, Milos Raonic, Tom...
251        Wimbledon  2018  {Roger Federer, Kei Nishikori, Milos Raonic, J...
252        Wimbledon  2019  {Roger Federer, Kei Nishikori, Sam Querrey, Gu...

[253 rows x 3 columns]

In [ ]:
#Put the set of players back into the original df
dfMerged = pd.merge(mastersPlus, Top8Winners, on=['tourney_name', 'year'], how='left')

dfMerged

,tourney_name,surface,match_num,winner_seed,winner_name,winner_ht,winner_ioc,winner_age,loser_seed,loser_name,...,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,year,top8_players
0,Australian Open,Hard,1,1.0,Gustavo Kuerten,190.0,BRA,24.347707,NaN,Gaston Gaudio,...,6.0,153.0,85.0,61.0,29.0,22.0,10.0,16.0,2001,"{Yevgeny Kafelnikov, Sebastien Grosjean, Arnau..."
1,Australian Open,Hard,2,NaN,Greg Rusedski,193.0,GBR,27.359343,NaN,Marcos Ondruska,...,6.0,124.0,70.0,46.0,27.0,19.0,3.0,8.0,2001,"{Yevgeny Kafelnikov, Sebastien Grosjean, Arnau..."
2,Australian Open,Hard,3,NaN,Stefan Koubek,175.0,AUT,24.035592,NaN,Jeff Tarango,...,3.0,106.0,61.0,41.0,23.0,18.0,5.0,11.0,2001,"{Yevgeny Kafelnikov, Sebastien Grosjean, Arnau..."
3,Australian Open,Hard,4,NaN,Lars Burgsmuller,183.0,GER,25.111567,NaN,Daniel Elsner,...,11.0,182.0,98.0,74.0,34.0,27.0,11.0,18.0,2001,"{Yevgeny Kafelnikov, Sebastien Grosjean, Arnau..."
4,Australian Open,Hard,5,NaN,Nicolas Escude,185.0,FRA,24.785763,NaN,Juan Balcells,...,1.0,169.0,113.0,77.0,30.0,26.0,12.0,18.0,2001,"{Yevgeny Kafelnikov, Sebastien Grosjean, Arnau..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21037,Paris Masters,Hard,296,4.0,Alexander Zverev,198.0,GER,23.537303,12.0,Stan Wawrinka,...,1.0,65.0,36.0,23.0,14.0,11.0,0.0,4.0,2020,"{Stan Wawrinka, Diego Schwartzman, Alexander Z..."
21038,Paris Masters,Hard,297,1.0,Rafael Nadal,185.0,ESP,34.417522,9.0,Pablo Carreno Busta,...,0.0,92.0,68.0,46.0,11.0,14.0,4.0,7.0,2020,"{Stan Wawrinka, Diego Schwartzman, Alexander Z..."
21039,Paris Masters,Hard,298,3.0,Daniil Medvedev,198.0,RUS,24.725530,10.0,Milos Raonic,...,1.0,68.0,47.0,38.0,6.0,11.0,1.0,3.0,2020,"{Stan Wawrinka, Diego Schwartzman, Alexander Z..."
21040,Paris Masters,Hard,299,4.0,Alexander Zverev,198.0,GER,23.537303,1.0,Rafael Nadal,...,0.0,68.0,46.0,29.0,12.0,11.0,5.0,8.0,2020,"{Stan Wawrinka, Diego Schwartzman, Alexander Z..."
21041,Paris Masters,Hard,300,3.0,Daniil Medvedev,198.0,RUS,24.725530,4.0,Alexander Zverev,...,3.0,102.0,76.0,51.0,9.0,15.0,6.0,10.0,2020,"{Stan Wawrinka, Diego Schwartzman, Alexander Z..."

In [ ]:
#Run through each tournament and only keep rows that match with the top 8 players from the tournament
Filtered = dfMerged[dfMerged.apply(lambda x: x['winner_name'] in x['top8_players'], axis=1)].drop(columns=['top8_players'])

Filtered

,tourney_name,surface,match_num,winner_seed,winner_name,winner_ht,winner_ioc,winner_age,loser_seed,loser_name,...,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,year
7,Australian Open,Hard,8,15.0,Arnaud Clement,173.0,FRA,23.080082,NaN,Tommy Robredo,...,2.0,4.0,84.0,46.0,28.0,18.0,15.0,6.0,12.0,2001
15,Australian Open,Hard,16,4.0,Yevgeny Kafelnikov,190.0,RUS,26.907598,NaN,Jens Knippschild,...,7.0,1.0,81.0,36.0,24.0,15.0,13.0,6.0,12.0,2001
23,Australian Open,Hard,24,16.0,Sebastien Grosjean,175.0,FRA,22.633812,NaN,Ivan Ljubicic,...,10.0,2.0,110.0,61.0,40.0,20.0,14.0,5.0,10.0,2001
28,Australian Open,Hard,29,NaN,Carlos Moya,190.0,ESP,24.386037,NaN,Marcelo Rios,...,2.0,3.0,93.0,52.0,33.0,14.0,13.0,11.0,18.0,2001
32,Australian Open,Hard,33,6.0,Andre Agassi,180.0,USA,30.715948,NaN,Jiri Vanek,...,12.0,5.0,110.0,58.0,35.0,20.0,13.0,13.0,20.0,2001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21037,Paris Masters,Hard,296,4.0,Alexander Zverev,198.0,GER,23.537303,12.0,Stan Wawrinka,...,2.0,1.0,65.0,36.0,23.0,14.0,11.0,0.0,4.0,2020
21038,Paris Masters,Hard,297,1.0,Rafael Nadal,185.0,ESP,34.417522,9.0,Pablo Carreno Busta,...,4.0,0.0,92.0,68.0,46.0,11.0,14.0,4.0,7.0,2020
21039,Paris Masters,Hard,298,3.0,Daniil Medvedev,198.0,RUS,24.725530,10.0,Milos Raonic,...,12.0,1.0,68.0,47.0,38.0,6.0,11.0,1.0,3.0,2020
21040,Paris Masters,Hard,299,4.0,Alexander Zverev,198.0,GER,23.537303,1.0,Rafael Nadal,...,5.0,0.0,68.0,46.0,29.0,12.0,11.0,5.0,8.0,2020
21041,Paris Masters,Hard,300,3.0,Daniil Medvedev,198.0,RUS,24.725530,4.0,Alexander Zverev,...,11.0,3.0,102.0,76.0,51.0,9.0,15.0,6.0,10.0,2020

In [ ]:
from google.colab import files
#Export df into csv file
pd.DataFrame(Filtered).to_csv('Top8_TourneyData.csv', index=False)

#Download file to computer rather than colab storage
files.download('Top8_TourneyData.csv')

In [ ]:
#Drop a bunch of other unnecessary cols - also adding more, so no need for extraneous info
Filtered = Filtered.drop(columns = ['match_num', 'winner_seed', 'loser_seed', 'best_of', 'minutes', 'winner_ioc', 'loser_ioc'])
#Add new statistical columns:
#Total points won throughout match
Filtered['winner_total_points'] = (
    Filtered['w_1stWon'] + Filtered['w_2ndWon'] + (Filtered['l_svpt'] - Filtered['l_1stWon'] - Filtered['l_2ndWon'])
)
Filtered['loser_total_points'] = (
    Filtered['l_1stWon'] + Filtered['l_2ndWon'] + (Filtered['w_svpt'] - Filtered['w_1stWon'] - Filtered['w_2ndWon'])
)
#Points difference - higher numbers is better/more dominant
Filtered['points_difference'] = (
    Filtered['winner_total_points'] - Filtered['loser_total_points']
)
#1st serve percentages - % of total serves that landed in first time
Filtered['w_1stSv%'] = (Filtered['w_1stIn'] / Filtered['w_svpt'] * 100).round(2)
Filtered['l_1stSv%'] = (Filtered['l_1stIn'] / Filtered['l_svpt'] * 100).round(2)
#1st serve percentage difference - higher number is better/more first time accuracy
Filtered['1stSv%_difference'] = (Filtered['w_1stSv%'] - Filtered['l_1stSv%']).round(2)
#1st serve win percentage - %of first time serves won by the server
Filtered['w_1stSvWin%'] = (Filtered['w_1stWon'] / Filtered['w_1stIn'] * 100).round(2)
Filtered['l_1stSvWin%'] = (Filtered['l_1stWon'] / Filtered['l_1stIn'] * 100).round(2)
#Difference equation - higher number is better/more dominant
Filtered['1stSvWin%_difference'] = (Filtered['w_1stSvWin%'] - Filtered['l_1stSvWin%']).round(2)
#2nd serve win percentage - %of 2nd time serves won by the server
Filtered['w_2ndSvWin%'] = ((Filtered['w_2ndWon']) / (Filtered['w_svpt'] - Filtered['w_1stIn']) * 100).round(2)
Filtered['l_2ndSvWin%'] = ((Filtered['l_2ndWon']) / (Filtered['l_svpt'] - Filtered['l_1stIn']) * 100).round(2)
#Difference equation - higher number is better/More secure with 2nd serves
Filtered['2ndSvWin%_difference'] = (Filtered['w_2ndSvWin%'] - Filtered['l_2ndSvWin%']).round(2)
#% of aces served by winner - higher is better
Filtered['ace%'] = (Filtered['w_ace'] / (Filtered['w_ace'] + Filtered['l_ace']) * 100).round(2)
#% of break points faced - lower is better, more secure with service game
Filtered['bpFaced%'] = (Filtered['w_bpFaced'] / (Filtered['w_bpFaced'] + Filtered['l_bpFaced']) * 100).round(2)

In [ ]:
stat_cols = [
    'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon',
    'w_bpSaved', 'w_bpFaced', 'winner_total_points', 'w_1stSv%', 'w_1stSvWin%',
    'w_2ndSvWin%', 'w_SvGms',
    'l_ace', 'l_df', 'l_svpt', 'l_1stIn', 'l_1stWon', 'l_2ndWon',
    'l_bpSaved', 'l_bpFaced', 'loser_total_points', 'l_1stSv%', 'l_1stSvWin%',
    'l_2ndSvWin%', 'l_SvGms',
    'points_difference', '1stSv%_difference', '1stSvWin%_difference',
    '2ndSvWin%_difference', 'ace%', 'bpFaced%'
]
Top8_Aggregated = Filtered.groupby(['tourney_name', 'year'])[stat_cols].mean().round(2)

#Deltas are first calculated by row-level and then are recalculated when aggregating
Top8_Aggregated['ace%'] = (Top8_Aggregated['w_ace'] / (Top8_Aggregated['w_ace'] + Top8_Aggregated['l_ace']) * 100).round(2)
Top8_Aggregated['bpFaced%'] = (Top8_Aggregated['w_bpFaced'] / (Top8_Aggregated['w_bpFaced'] + Top8_Aggregated['l_bpFaced']) * 100).round(2)
Top8_Aggregated['points_difference'] = (Top8_Aggregated['winner_total_points'] - Top8_Aggregated['loser_total_points'])
Top8_Aggregated['1stSv%_difference'] = (Top8_Aggregated['w_1stSv%'] - Top8_Aggregated['l_1stSv%']).round(2)
Top8_Aggregated['1stSvWin%_difference'] = (Top8_Aggregated['w_1stSvWin%'] - Top8_Aggregated['l_1stSvWin%']).round(2)
Top8_Aggregated['2ndSvWin%_difference'] = (Top8_Aggregated['w_2ndSvWin%'] - Top8_Aggregated['l_2ndSvWin%']).round(2)
Top8_Aggregated

                      w_ace  w_df  w_svpt  w_1stIn  w_1stWon  w_2ndWon  \
tourney_name    year
Australian Open 2001   8.03  3.67  100.59    61.38     47.13     21.56
                2002  11.97  3.41  111.41    62.74     47.05     26.46
                2003   8.47  2.92  100.55    60.18     45.58     22.16
                2004  10.59  2.23   95.31    55.62     43.87     21.87
                2005  10.51  2.87  101.95    62.51     47.87     21.56
...                     ...   ...     ...      ...       ...       ...
Wimbledon       2015  12.59  2.74  106.56    68.69     55.36     21.92
                2016  15.36  2.46  104.15    65.87     54.74     21.67
                2017  15.97  2.87  101.51    65.59     53.69     21.18
                2018  18.13  3.18  106.92    73.36     59.90     19.38
                2019   8.92  2.90  101.44    65.72     51.95     20.51

                      w_bpSaved  w_bpFaced  winner_total_points  w_1stSv%  \
tourney_name    year
Australian Open 2001       3.90       6.10               115.92     61.63
                2002       4.62       7.41               124.59     56.87
                2003       4.03       6.55               116.63     60.21
                2004       3.97       5.46               108.10     58.81
                2005       4.49       6.67               117.62     61.85
...                         ...        ...                  ...       ...
Wimbledon       2015       2.95       4.13               119.54     64.50
                2016       3.28       4.59               120.82     63.48
                2017       3.59       4.77               116.62     64.56
                2018       2.95       4.15               125.38     68.38
                2019       3.56       4.95               115.92     64.96

                      ...  l_1stSv%  l_1stSvWin%  l_2ndSvWin%  l_SvGms  \
tourney_name    year  ...
Australian Open 2001  ...     56.59        65.67        43.43    16.41
                2002  ...     57.99        64.74        44.56    17.74
                2003  ...     57.64        62.42        43.71    16.61
                2004  ...     61.04        64.33        42.69    15.33
                2005  ...     58.69        62.77        45.17    16.54
...                   ...       ...          ...          ...      ...
Wimbledon       2015  ...     61.59        69.71        48.04    17.87
                2016  ...     63.01        68.26        45.82    17.51
                2017  ...     62.81        69.14        46.65    17.21
                2018  ...     63.65        67.64        47.69    18.56
                2019  ...     60.52        67.76        45.69    16.87

                      points_difference  1stSv%_difference  \
tourney_name    year
Australian Open 2001              22.59               5.04
                2002              17.92              -1.12
                2003              21.42               2.57
                2004              21.23              -2.23
                2005              22.34               3.16
...                                 ...                ...
Wimbledon       2015              19.72               2.91
                2016              22.20               0.47
                2017              20.88               1.75
                2018              23.35               4.73
                2019              21.51               4.44

                      1stSvWin%_difference  2ndSvWin%_difference   ace%  \
tourney_name    year
Australian Open 2001                 12.03                 12.70  48.08
                2002                 10.74                 10.78  59.55
                2003                 13.63                 11.76  57.27
                2004                 15.06                 12.84  66.31
                2005                 14.75                 11.39  60.30
...                                    ...                   ...    ...
Wimbledon       2015                 11.29                 10.68  54.74
                2016                 15.04                 11.11  62.67
                2017                 12.86                 13.75  63.57
                2018                 15.05                 11.44  64.27
                2019                 12.33                 13.32  45.53

                      bpFaced%
tourney_name    year
Australian Open 2001     32.19
                2002     35.12
                2003     32.93
                2004     33.27
                2005     33.77
...                        ...
Wimbledon       2015     29.82
                2016     29.88
                2017     33.03
                2018     27.21
                2019     31.23

[253 rows x 32 columns]

In [ ]:
from google.colab import files
#Export df into csv file
pd.DataFrame(Top8_Aggregated).to_csv('Top8_Aggregated.csv', index=True)
pd.DataFrame(Top8_Aggregated).to_excel('Top8_Aggregated.xlsx', index=True)
#Download file to computer rather than colab storage
files.download('Top8_Aggregated.csv')
files.download('Top8_Aggregated.xlsx')